-------------------- 
Measuring Performance in Regression models
-------------------- 
Let's take some values generated from a model (predicted), the real ones (observed) and the associated real ones

```{r}
observed <- c(0.22,  0.83, -0.12, 0.89, -0.23, -1.30, -0.15, -1.4,              0.62,  0.99, -0.18, 0.32,  0.34, -0.30,  0.04, -0.87,  0.55, -1.30, -1.15, 0.20)
predicted <- c(0.24,  0.78, -0.66,  0.53, 0.70, -0.75, -0.41, -0.43,                0.49,  0.79, -1.19,  0.06, 0.75, -0.07,  0.43, -0.42, -0.25, -0.64, -1.26, -0.07)
residualValues <- observed - predicted
```

Let's see some summary 

```{r}
summary(residualValues)
```

We're near zero.


---- Observed values versus predicted values
It is a good idea to plot the values on a common scale.

```{r}
axisRange <- extendrange(c(observed, predicted))
```
Now we plot observed vs predicted using a 45 degree reference line 
```{r,fig.keep='all'}
plot(observed, predicted,  
     ylim = axisRange,
     xlim = axisRange)
abline(0, 1, col = "darkgrey", lty = 2)

```
Now let's see the predicted vs residuals 
```{r}
plot(predicted, residualValues,  
     ylim = axisRange,
     xlim = axisRange)
abline(0, 0, col = "darkgrey", lty = 2)
```

----------------------------------------------------------------------------
Let's try the same but with some variations:
we take the square of the predicted (our algorithm is working wrong)

```{r}
observed <- c(0.22,  0.83, -0.12, 0.89, -0.23, -1.30, -0.15, -1.4,              0.62,  0.99, -0.18, 0.32,  0.34, -0.30,  0.04, -0.87,  0.55, -1.30, -1.15, 0.20)
predicted <- predicted^2
residualValues <- observed - predicted
```


```{r}
plot(observed, predicted,  
     ylim = axisRange,
     xlim = axisRange)
abline(0, 1, col = "darkgrey", lty = 2)
```


```{r}
plot(predicted, residualValues, ylab = "residual")
abline(h = 0, col = "darkgrey", lty = 2)
```

